// AUTO-GENERATED from scripts/gguf_keys.py - do not edit.
#pragma once

#define DA_KV_ARCH "depthanything3.arch"
#define DA_KV_CHECKPOINT_NAME "depthanything3.checkpoint_name"
#define DA_KV_PATCH_SIZE "depthanything3.patch_size"
#define DA_KV_IMAGE_SIZE "depthanything3.image_size"
#define DA_KV_TASK_CAPS "depthanything3.task_caps"
#define DA_KV_VIT_EMBED_DIM "depthanything3.vit.embed_dim"
#define DA_KV_VIT_DEPTH "depthanything3.vit.depth"
#define DA_KV_VIT_NUM_HEADS "depthanything3.vit.num_heads"
#define DA_KV_VIT_HEAD_DIM "depthanything3.vit.head_dim"
#define DA_KV_VIT_MLP_HIDDEN "depthanything3.vit.mlp_hidden"
#define DA_KV_VIT_NUM_REGISTER "depthanything3.vit.num_register_tokens"
#define DA_KV_VIT_INIT_VALUES "depthanything3.vit.init_values"
#define DA_KV_VIT_ALT_START "depthanything3.vit.alt_start"
#define DA_KV_VIT_ROPE_START "depthanything3.vit.rope_start"
#define DA_KV_VIT_QKNORM_START "depthanything3.vit.qknorm_start"
#define DA_KV_VIT_ROPE_FREQ "depthanything3.vit.rope_freq"
#define DA_KV_VIT_CAT_TOKEN "depthanything3.vit.cat_token"
#define DA_KV_VIT_QKV_BIAS "depthanything3.vit.qkv_bias"
#define DA_KV_VIT_LN_EPS "depthanything3.vit.ln_eps"
#define DA_KV_VIT_INTERP_OFFSET "depthanything3.vit.interpolate_offset"
#define DA_KV_VIT_INTERP_ANTIALIAS "depthanything3.vit.interpolate_antialias"
#define DA_KV_VIT_POS_EMBED_GRID "depthanything3.vit.pos_embed_grid"
#define DA_KV_VIT_OUT_LAYERS "depthanything3.vit.out_layers"
#define DA_KV_IMG_MEAN "depthanything3.img.mean"
#define DA_KV_IMG_STD "depthanything3.img.std"
#define DA_KV_IMG_RESIZE_MODE "depthanything3.img.resize_mode"
#define DA_KV_IMG_RESIZE_TARGET "depthanything3.img.resize_target"
#define DA_KV_HEAD_FEATURES "depthanything3.head.features"
#define DA_KV_HEAD_OUT_CHANNELS "depthanything3.head.out_channels"
#define DA_KV_HEAD_OUTPUT_DIM "depthanything3.head.output_dim"
#define DA_KV_HEAD_POS_EMBED "depthanything3.head.pos_embed"
#define DA_KV_HEAD_DOWN_RATIO "depthanything3.head.down_ratio"
#define DA_KV_HEAD_ACTIVATION "depthanything3.head.activation"
#define DA_KV_HEAD_CONF_ACTIVATION "depthanything3.head.conf_activation"
#define DA_ARCH "depthanything3"
